plugins {
    id "com.android.application"
}

android {
    namespace "com.paperbook.cloud"
    compileSdk 35

    defaultConfig {
        applicationId "com.paperbook.cloud"
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName "9.2.0-email-auth"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".beta"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


dependencies {
    implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
}
